from django.conf.urls.defaults import *

urlpatterns = patterns('guider.skul.views',
    url(r'^$', 'root_view', name='main-page'),
    url(r'^student/register$', 'student_register', name='reg-student'),
    url(r'^teacher/addtopic$', 'teacher_addtopic', name='addtopic-teacher'),
    url(r'^teacher/adduzleg$', 'teacher_adduzleg', name='adduzleg-teacher'),
    url(r'^teacher/student$', 'teacher_student', name='student-teacher'),
    url(r'^teacher/news$', 'teacher_news', name='news-teacher'),
    url(r'^student$', 'student_home', name='home-student'),
    url(r'^teacher$', 'teacher_home', name='home-teacher'),
    url(r'^FAQ$', 'FAQ_home', name='home-FAQ'),
    url(r'^material$', 'ex_home', name='home-ex'),
    url(r'^contact$', 'contact', name='contact'),
    url(r'^student/login$', 'student_login', name='log-student'),
    url(r'^student/sedev$', 'student_sedev', name='sedev-student'),
    url(r'^student/yzleg/huvaari$', 'student_yzhuv', name='yzhuv-student'),
    url(r'^student/score$', 'student_score', name='score-student'),
    url(r'^contact/message$', 'contact_message', name='message_contact'),
    url(r'^narrinBichig$', 'nabi_home', name='home-nabi'),
    url(r'^narrinBichig/sendNews$', 'nabi_send', name='send-nabi'),
    url(r'^narrinBichig/uzleg$', 'nabi_uzleg', name='uzleg-nabi'),
    url(r'^narrinBichig/student$', 'nabi_student', name='student-nabi'),
    url(r'^narrinBichig/zar$', 'nabi_zar', name='zar-nabi'),
    url(r'^narrinBichig/teacher$', 'nabi_teacher', name='teacher-nabi'),
)
